[[plungins]]  
repo = 'Shougo/dein.vim'
              
[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml' 

[[plugins]] # file browse
repo = 'Shougo/unite.vim'

[[plugins]] # color scheme
repo = 'altercation/vim-colors-solarized'

[[plugins]] # Asynchronous Lint Engine
repo = 'w0rp/ale'

[[plugins]] # statusline plugin
repo = 'itchyny/lightline.vim'
