[[plungins]] # pgugin manager
repo = 'Shougo/dein.vim'
              
[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml' 

[[plugins]] # file browse
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup = 1
'''

[[plugins]] # require for deoplete
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]] # require for deoplete
repo = 'roxma/nvim-yarp'

[[plugins]] # color scheme
repo = 'altercation/vim-colors-solarized'

[[plugins]] # color scheme
repo = 'cocopon/iceberg.vim'

[[plugins]] # iceberg for lightline
repo = 'hallzy/lightline-iceberg'

[[plugins]] # Asynchronous Lint Engine
repo = 'w0rp/ale'
hook_add = '''
let g:ale_fixers = {
\  'ruby': ['rubocup'],
\}
let g:ale_sign_column_always = 1
let g:ale_sign_error = '×'
let g:ale_sign_warning = '⚠︎'
'''

[[plugins]] # statusline plugin
repo = 'itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
      \ 'colorscheme': 'iceberg',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'fugitive', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'fugitive': 'LightlineFugitive'
      \ },
      \ 'separator': { 'left': "\ue0b0", 'right': "\ue0b2" },
      \ 'subseparator': { 'left': "\ue0b1", 'right': "\ue0b3" }
      \ }
function! LightlineFugitive()
  if exists('*fugitive#head')
    let branch = fugitive#head()
    return branch !=# '' ? ''.branch : ''
  endif
  return ''
endfunction
'''

[[plugins]] # complete pairs
repo = 'tpope/vim-surround'

[[plugins]] # file system explorer
repo = 'scrooloose/nerdtree'
hook_add = '''
let g:NERDTreeShowBookmarks = 1
let g:NERDTreeShowHidden = 1
'''

[[plugins]] # nerdtree plugin
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]] # nerdtree plugin
repo = 'Xuyuanp/nerdtree-git-plugin'

[[plugins]] # git plugin
repo = "airblade/vim-gitgutter"

[[plugins]] #  help to end
repo = 'tpope/vim-endwise'

[[plugins]] # git
repo = 'tpope/vim-fugitive'

[[plugins]] # help to tag end
repo = 'alvan/vim-closetag'

[[plugins]] # create my vim cheatsheet
# :Cheat -> show cheatsheet
repo = 'reireias/vim-cheatsheet'
hook_add = '''
let g:cheatsheet#cheat_file = "cheatsheet.md"
'''
